# Create User
POST http://4.157.146.125:3000/users
Content-Type: application/json

{
  "name": "Chethan",
  "email": "chethan@gmail.com",
  "age": 20
}

###

# Get All Users
GET http://localhost:3000/users

###

# Get User by ID (replace `user_id` with an actual user ID)
GET http://localhost:3000/users/{user_id}

###

# Update User by ID (replace `user_id` with an actual user ID)
PUT http://localhost:3000/users/{user_id}
Content-Type: application/json

{
  "name": "Johnathan Doe",
  "email": "johnathan.doe@example.com",
  "age": 32
}

###

# Delete User by ID (replace `user_id` with an actual user ID)
DELETE http://localhost:3000/users/{user_id}

###
